# Generated by Django 4.0.5 on 2022-06-20 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
