# Generated by Django 4.0.5 on 2022-06-26 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recomendation',
            field=models.CharField(choices=[('MW', 'Must Watch'), ('SW', 'Should Watch'), ('AW', 'Avoid Watch'), ('NO', 'No Opinion')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
