# Generated by Django 4.0.5 on 2022-06-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='critic',
            new_name='movie',
        ),
    ]
