# Generated by Django 4.0.5 on 2022-06-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_movie_review_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recomendation',
            field=models.CharField(choices=[('Must Watch', 'MW'), ('Should Watch', 'SW'), ('Avoid Watch', 'AW'), ('No Opinion', 'NO')], default='No Opinion', max_length=50),
        ),
    ]
